name: Run golang app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3.5.3
      - name: Install golang
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20.5'
      - name: Test with the Go CLI
        run: go test
