name: Run golang app
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3.5.3
      - name: Setup golang
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20.5'
      - name: Test with the Go CLI
        run: go test
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3.6.0
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repo code
        uses: actions/checkout@v3.5.3
      - name: Setup golang
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20.5'
      - name: Build app
        run: go build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get repo code
        uses: actions/checkout@v3.5.3
      - name: Setup golang
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20.5'
      - name: Deploy app
        run: echo "deploying app.."
      
